languageCode = "en-us"
title = "Bulb Audit"
baseURL = "https://bulbenergy.github.io/bulb-audit/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "The **Bulb** inclusive design audit report."
  codePenUser = "Heydon"

[taxonomies]
  tag = "tags"
  priority = "priorities"
