languageCode = "en-us"
title = "Infusion"
baseURL = "https://heydon.github.io/infusion/"
canonifyURLs = true
theme = "infusion"
publishDir = "docs"

[params]
  description = "Documentation for the **Infusion** pattern library builder, built with **Infusion** itself."
  codePenUser = "Heydon"
