languageCode = "en-us"
title = "Bulb Audit"
baseURL = "https://heydon.github.io/bulb-audit/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "The **Bulb** inclusive design audit report."
  codePenUser = "Heydon"
