languageCode = "en-us"
title = "Infusion"
baseURL = "/"
theme = "infusion"

[params]
  description = "Documentation for the <strong>Infusion</strong> pattern library builder. This documentation is constructed using the builder itself."
  codePenUser = "Heydon"
