languageCode = "en-us"
title = "Inclusive Pattern Docs"
baseURL = "/"
theme = "inclusive-pattern-docs"

[params]
  description = "The pattern library for <strong>The Demo Project</strong>"
  codePenUser = "Heydon"
