languageCode = "en-us"
title = "Inclusive Pattern Docs"
baseURL = "/"
theme = "inclusive-pattern-docs"

[params]
  description = "Documentation for the <strong>Infusion</strong> pattern library builder. This documentation is constructed using the builder itself."
  codePenUser = "Heydon"
